services:
  - type: web
    name: harnesshub-backend
    env: docker
    dockerContext: ./back
    dockerfilePath: ./back/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: GITHUB_TOKEN
        sync: false
    region: singapore
    plan: starter
