[build]
builder = "nixpacks"
buildCommand = "npm install --omit=optional && npm run build"

[deploy]
startCommand = "node dist/src/main.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
